Add translations for table list
Byzanteam/jet-i18n pull request #71
Opened 2020-10-29 10:32 UTC by vanppo

2020-10-29 10:48 UTC, moonRider approved these changes

2020-10-29 12:08 UTC, Leecason approved these changes

2020-10-29 15:20 UTC, fahchen requested changes

2020-10-29 15:20 UTC, fahchen commented on assets/locale/lang/zh_CN.json
> +    "table": {
table 不应该和 workflow 一个等级

最顶级是 context：workflow，database 等，这里的结构
```
database
  - table
  - row
  - column
```

2020-10-30 01:42 UTC, Leecason approved these changes

2020-10-30 01:47 UTC, moonRider approved these changes

2020-10-30 01:47 UTC, fahchen approved these changes

2020-10-30 01:47 UTC, merged