Feat/workflow case
Byzanteam/jet-i18n pull request #73
Opened 2020-11-03 07:31 UTC by Leecason

2020-11-03 07:34 UTC, fahchen commented on assets/locale/lang/zh_CN.json
> +        "case_table": {
case_table 是什么哦？

2020-11-03 07:36 UTC, moonRider requested changes

2020-11-03 07:36 UTC, moonRider commented on assets/locale/lang/zh_CN.json
> +        "case_table": {
这个词就是 case 吧，table 只是业务那边展示为 table 的，state 也是 case 的，不是case_table 的

2020-11-03 07:38 UTC, Leecason commented on assets/locale/lang/zh_CN.json
> +        "case_table": {
就是渲染 case 的表格

2020-11-03 07:39 UTC, Leecason commented on assets/locale/lang/zh_CN.json
> +        "case_table": {
上面不是有个 workflow list 么，也是业务那边的呀

2020-11-03 07:48 UTC, moonRider requested changes

2020-11-03 07:48 UTC, moonRider commented on assets/locale/lang/zh_CN.json
> +        "case_table": {
那state怎么解呢？

2020-11-03 07:49 UTC, moonRider commented on assets/locale/lang/zh_CN.json
> +        "case_table": {
```
case: {
  state: { ... }
  table: { ... }
}
```

2020-11-03 07:55 UTC, Leecason commented on assets/locale/lang/zh_CN.json
> +        "case_table": {
这里的 case_state，是针对 table 这个场景的翻译，和普通的不一样
running 要翻译成「未完成」而不是「进行中」

2020-11-03 08:17 UTC, moonRider approved these changes

2020-11-03 09:06 UTC, fahchen commented on assets/locale/lang/zh_CN.json
> +        "case_table": {
这里可能要调整一下
case 是没有对应的 table 的，是 project 可以设置 tables，然后在对应的 task 下显示（这里是过滤为当前 task 的 rows）

2020-11-03 09:06 UTC, fahchen commented on assets/locale/lang/zh_CN.json
> +        "case_table": {
你截图一下呢，我看下具体是在哪显示用的这个翻译？

2020-11-03 12:57 UTC, Leecason commented on assets/locale/lang/zh_CN.json
> +        "case_table": {
<img width="789" alt="截屏2020-11-0320 56 58" src="https://user-images.githubusercontent.com/17562078/97987959-1debb600-1e17-11eb-9e44-9b0e80030767.png">

2020-11-04 00:53 UTC, fahchen approved these changes

2020-11-04 01:21 UTC, merged